# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  decorations: none
  padding:
    x: 3
    y: 3

font:
  normal:
    family: PragmataProMono Nerd Font
  size: 14.0

# (One Dark)
colors:
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'
    bright_foreground: '0xe6efff'
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'
  dim:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  save_to_clipboard: true

key_bindings:
  # [alacritty] launch new instance (doesn't work)
  - { key: N, mods: Command|Alt, action: SpawnNewInstance }

  # [alacritty] quit instance
  # also add in macOS System Preferences -> Keyboard -> Shortcuts -> App Shortcuts 
  - { key: Q, mods: Command|Alt, action: Quit }

  # [tmux] launch command mode
  - { key: LBracket, mods: Command, chars: "\x13\x5b" }

  # [tmux] launch the session switcher
  - { key: K, mods: Command, chars: "\x13\x77" }

  # [tmux] switch to last session
  - { key: L, mods: Command, chars: "\x13\x4c" }

  # [tmux] detach the current client
  # (make sure and override alacritty's default cmd-q in macOS)
  - { key: Q, mods: Command, chars: "\x13\x64" }

  # [tmux] create a new window
  - { key: T, mods: Command, chars: "\x13\x63" }

  # [tmux] split the current pane, horizontal / vertical
  - { key: N, mods: Command, chars: "\x13\x22" }
  - { key: N, mods: Command|Shift, chars: "\x13\x25" }

  # [tmux] kill the current pane (and window if last pane)
  - { key: W, mods: Command, chars: "\x13\x78" }

  # [tmux] kill the current window (and exit if last window)
  - { key: X, mods: Command, chars: "\x13\x26" }

  # [tmux] rename the current window
  - { key: Comma, mods: Command, chars: "\x13\x2c" }

  # [tmux] rename the current session
  - { key: Period, mods: Command, chars: "\x13\x24" }

  # [tmux] go to the previous and next windoww
  - { key: LBracket, mods: Command|Shift, chars: "\x13\x70" }
  - { key: RBracket, mods: Command|Shift, chars: "\x13\x6e" }

  # [tmux] select windows 1-9
  - { key: Key1, mods: Command, chars: "\x13\x31" }
  - { key: Key2, mods: Command, chars: "\x13\x32" }
  - { key: Key3, mods: Command, chars: "\x13\x33" }
  - { key: Key4, mods: Command, chars: "\x13\x34" }
  - { key: Key5, mods: Command, chars: "\x13\x35" }
  - { key: Key6, mods: Command, chars: "\x13\x36" }
  - { key: Key7, mods: Command, chars: "\x13\x37" }
  - { key: Key8, mods: Command, chars: "\x13\x38" }
  - { key: Key9, mods: Command, chars: "\x13\x39" }

  # [tmux] break the current pane out into its own window
  - { key: T, mods: Command|Shift, chars: "\x13\x21" }

  # [tmux] toggle the zoom state of the current pane
  - { key: Z, mods: Command, chars: "\x13\x7a" }

  # [vim] type <escape>:w<enter> to save
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" }

  # [shell] type clear<enter> to clear screen
  - { key: L, mods: Command|Shift, chars: "\x63\x6c\x65\x61\x72\x0a" }

  # [shell] type reset<enter> for clear screen & scroll back buffer
  - { key: K, mods: Command|Shift, chars: "\x72\x65\x73\x65\x74\x0a" }

  # [shell] type lf<enter> to launch file finder
  - { key: F, mods: Command, chars: "\x6c\x66\x0a" }

  # [shell] makes these work as they are
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: C, mods: Alt, chars: "\x1bc" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: Q, mods: Alt, chars: "\x1b\x71" }
  - { key: Y, mods: Alt, chars: "\x1b\x79" }
  - { key: U, mods: Alt, chars: "\x1b\x75" }
  - { key: I, mods: Alt, chars: "\x1b\x69" }
  - { key: O, mods: Alt, chars: "\x1b\x6f" }
  - { key: Q, mods: Control, chars: "\x11" }
  - { key: Slash, mods: Control, chars: "\x1f" } # it beeps
