[env]
TERM = "xterm-256color"

[window]
decorations = "none"

[window.padding]
x = 3
y = 3

[colors]
[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[font]
size = 12.0

[font.normal]
family = "MonoLisa Nerd Font"

[scrolling]
history = 20000

# [alacritty] quit instance
# also add in macOS System Preferences -> Keyboard -> Shortcuts -> App Shortcuts
[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command|Alt"

# [tmux] launch command mode
[[keyboard.bindings]]
chars = "\u0013["
key = "LBracket"
mods = "Command"

# [tmux] launch the session switcher
[[keyboard.bindings]]
chars = "\u0013w"
key = "K"
mods = "Command"

# [tmux] switch to last session
[[keyboard.bindings]]
chars = "\u0013L"
key = "L"
mods = "Command"


# [tmux] detach the current client
# (make sure and override alacritty's default cmd-q in macOS)
[[keyboard.bindings]]
chars = "\u0013d"
key = "Q"
mods = "Command"

# [tmux] create a new window
[[keyboard.bindings]]
chars = "\u0013c"
key = "T"
mods = "Command"

# [tmux] split the current pane, horizontal
[[keyboard.bindings]]
chars = "\u0013\""
key = "N"
mods = "Command"

# [tmux] split the current pane, vertical
[[keyboard.bindings]]
chars = "\u0013%"
key = "N"
mods = "Command|Shift"

# [tmux] kill the current pane (and window if last pane)
[[keyboard.bindings]]
chars = "\u0013x"
key = "W"
mods = "Command"

# [tmux] rename the current window
[[keyboard.bindings]]
chars = "\u0013,"
key = "Comma"
mods = "Command"

# [tmux] rename the current session
[[keyboard.bindings]]
chars = "\u0013$"
key = "Period"
mods = "Command"

###
# [tmux] select windows 1-9
###
[[keyboard.bindings]]
chars = "\u00131"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00132"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00133"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00134"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00135"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00136"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00137"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00138"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00139"
key = "Key9"
mods = "Command"

# [tmux] break the current pane out into its own window
[[keyboard.bindings]]
chars = "\u0013!"
key = "T"
mods = "Command|Shift"

# [tmux] toggle the zoom state of the current pane
[[keyboard.bindings]]
chars = "\u0013z"
key = "Z"
mods = "Command"

# [shell] type lf<enter> to launch file finder
[[keyboard.bindings]]
chars = """
lf
"""
key = "F"
mods = "Command"

###
# [shell] makes these work as they are
###
[[keyboard.bindings]]
chars = "\u0004"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

