[selection]
save_to_clipboard = true

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[font]
size = 12.0

[font.normal]
family = "MonoLisa Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command|Alt"

[[keyboard.bindings]]
chars = "\u0013["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013w"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013d"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013\""
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013%"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013&"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013$"
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00131"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00132"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00133"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00134"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00135"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00136"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00137"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00138"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00139"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = """
lf
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[scrolling]
history = 20000

[window]
decorations = "none"

[window.padding]
x = 3
y = 3
