require('w.globals')
require('w.defaults')
require('w.keymaps')
require('w.treesitter')
require('w.diagnostic')
require('w.autocmds')
require('w.usercmds')

require('w.lsp').setup()
require('w.winbar').setup()
