require('w.globals')
require('w.defaults')
require('w.keymaps')
require('w.treesitter')
require('w.autocmds')
require('w.usercmds')
require('w.qf')

require('w.lsp').setup()
require('w.diagnostic').setup()
require('w.winbar').setup()
