--
-- which-key
-- https://github.com/folke/which-key.nvim
--

return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  init = function()
    vim.o.timeout = true
    vim.o.timeoutlen = 300
  end,
  dependencies = {},
  config = function()
    local wk = require('which-key')

    wk.setup({
      preset = 'helix',
      show_help = false,
      plugins = {
        spelling = {
          enabled = false,
        },
      },
    })

    wk.add({
      { '/', hidden = true },
      { '?', hidden = true },
      { 'h', hidden = true },
      { 'j', hidden = true },
      { 'k', hidden = true },
      { 'l', hidden = true },
      { 'n', hidden = true },
      { '<2-LeftMouse>', desc = 'Match double clicked word' },
      { '<C-f>', desc = 'snacks', icon = { icon = '󱥳', color = 'purple' } },
      { '<leader>e', desc = 'rip substitute', icon = { icon = '󰬳', color = 'orange' } },
      { '<leader>o', icon = { icon = '', color = 'cyan' } },
      { '<leader>r', desc = 'substitute word(s)', icon = { icon = '󰬳', color = 'orange' } },
      { '<leader>a', group = 'ai', icon = { icon = '󰚩', color = 'grey' } },
      { '<leader>ab', icon = { icon = '󱀹', color = 'blue' } },
      { '<leader>ad', icon = { icon = '', color = 'red' } },
      { '<leader>al', icon = { icon = '󰚩', color = 'grey' } },
      { '<leader>ap', icon = { icon = '󰉻', color = 'purple' } },
      { '<leader>as', desc = 'send selection', icon = { icon = '󰵴', color = 'cyan' }, mode = 'v' },
      { '<leader>at', icon = { icon = '󰵴', color = 'cyan' } },
      { '<leader>d', group = 'debug', icon = { icon = '', color = 'red' } },
      { '<leader>de', icon = { icon = '', color = 'red' } },
      { '<leader>dh', icon = { icon = '', color = 'blue' } },
      { '<leader>dl', icon = { icon = '', color = 'green' } },
      { '<leader>do', icon = { icon = '', color = 'cyan' } },
      { '<leader>dR', icon = { icon = '', color = 'orange' } },
      { '<leader>dr', icon = { icon = '', color = 'green' } },
      { '<leader>dv', icon = { icon = '󰌨', color = 'blue' } },
      { '<leader>dt', icon = { icon = '', color = 'blue' } },
      { '<leader>du', icon = { icon = '', color = 'yellow' } },
      { '<leader>db', icon = { icon = '', color = 'red' } },
      { '<leader>dB', icon = { icon = '', color = 'red' } },
      { '<leader>dd', icon = { icon = '', color = 'green' } },
      { 'gd', desc = 'diagnostics', icon = { icon = '', color = 'yellow' } },
      { 'gdd', icon = { icon = '󰧮', color = 'red' } },
      { 'gdh', icon = { icon = '', color = 'blue' } },
      { 'gdn', icon = { icon = '󰮱', color = 'yellow' } },
      { 'gdp', icon = { icon = '󰮳', color = 'yellow' } },
      { 'gdw', icon = { icon = '󱔘', color = 'red' } },
      { '<leader>f', icon = { icon = '󰱼', color = 'blue' } },
      { '<leader>b', icon = { icon = '󰱼', color = 'cyan' } },
      { '<leader>s', icon = { icon = '󱎸', color = 'green' } },
      { '<leader>w', icon = { icon = '󱎸', color = 'green' } },
      { '<leader>g', icon = { icon = '󰊢', color = 'orange' } },
      { '<leader>h', desc = 'git', icon = { icon = '', color = 'green' } },
      { '<leader>hb', icon = { icon = '', color = 'green' } },
      { '<leader>hh', icon = { icon = '', color = 'blue' } },
      { '<leader>hF', icon = { icon = '', color = 'yellow' } },
      { '<leader>hn', icon = { icon = '󰮱', color = 'green' } },
      { '<leader>hp', icon = { icon = '󰮳', color = 'green' } },
      { '<leader>hr', icon = { icon = '', color = 'red' } },
      { '<leader>hR', icon = { icon = '', color = 'red' } },
      { '<leader>hs', icon = { icon = '', color = 'green' } },
      { '<leader>hS', icon = { icon = '󰕌', color = 'yellow' } },
      { '<leader>ht', icon = { icon = '󱂧', color = 'orange' } },
      { '<leader>hB', icon = { icon = '󰕌', color = 'yellow' } },
      { '<leader>hI', icon = { icon = '', color = 'blue' } },
      { '<leader>hi', icon = { icon = '', color = 'blue' } },
      { '<leader>hl', icon = { icon = '󰝖', color = 'grey' } },
      { '<leader>hd', desc = 'diff', icon = { icon = '', color = 'purple' } },
      { '<leader>hdt', icon = { icon = '', color = 'purple' } },
      { '<leader>hdo', icon = { icon = '', color = 'purple' } },
      { '<leader>l', desc = 'toggle loclist', icon = { icon = '󰝖', color = 'grey' } },
      { '<leader>q', desc = 'toggle quickfix', icon = { icon = '󰝖', color = 'azure' } },
      { '<leader>t', desc = 'testing', icon = { icon = '󰙨', color = 'yellow' } },
      { '<leader>ta', icon = { icon = '󱘖', color = 'yellow' } },
      { '<leader>tf', icon = { icon = '', color = 'green' } },
      { '<leader>th', icon = { icon = '', color = 'blue' } },
      { '<leader>tl', icon = { icon = '', color = 'green' } },
      { '<leader>tt', icon = { icon = '󰣉', color = 'green' } },
      { '<leader>tn', icon = { icon = '󰮱', color = 'red' } },
      { '<leader>tp', icon = { icon = '󰮳', color = 'red' } },
      { '<leader>to', icon = { icon = '', color = 'yellow' } },
      { '<leader>ts', icon = { icon = '', color = 'yellow' } },
      { '<leader>tw', icon = { icon = '󱎴', color = 'orange' } },
      { '<leader>x', desc = 'execute current line', icon = { icon = '󰢱', color = 'blue' } },
      { '<leader><leader>', group = 'miscellaneous', icon = { icon = '󱐖', color = 'azure' } },
      { '<leader><leader>x', desc = 'execute current file', icon = { icon = '󰢱', color = 'green' } },
      { '<leader><leader>s', desc = 'reload snippets', icon = { icon = '', color = '' } },
      { '<leader>y', desc = 'copy to system clipboard', icon = { icon = '', color = 'yellow' } },
      { 'Y', desc = 'Yank to end of line' },
      { 'gl', desc = 'lsp', icon = { icon = '', color = 'purple' } },
      { 'gld', icon = { icon = '', color = 'green' } },
      { 'glD', icon = { icon = '', color = 'green' } },
      { 'gly', icon = { icon = '', color = 'green' } },
      { 'glt', icon = { icon = '', color = 'green' } },
      { 'gli', icon = { icon = '', color = 'green' } },
      { 'glr', icon = { icon = '', color = 'green' } },
      { 'glS', icon = { icon = '', color = 'cyan' } },
      { 'gls', icon = { icon = '', color = 'orange' } },
      { 'glw', icon = { icon = '', color = 'orange' } },
      { 'gll', icon = { icon = '', color = 'yellow' } },
      { 'gla', icon = { icon = '', color = 'yellow' } },
      { 'glh', icon = { icon = '󰙅', color = 'blue' } },
      { 'glK', icon = { icon = '', color = 'blue' } },
      { 'glo', icon = { icon = '', color = 'yellow' } },
      { 'glH', icon = { icon = '', color = 'yellow' } },
      { 'glR', icon = { icon = '󰑕', color = 'red' } },
      { 'glf', icon = { icon = '󰉢', color = 'blue' } },
      { 'glc', icon = { icon = '', color = 'green' } },
      { 'glC', icon = { icon = '', color = 'orange' } },
      { 'gr', desc = 'selection', icon = { icon = '󰸱', color = 'cyan' } },
    })
  end,
}
