--
-- which-key
-- https://github.com/folke/which-key.nvim
--

return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  init = function()
    vim.o.timeout = true
    vim.o.timeoutlen = 300
  end,
  dependencies = {
    'echasnovski/mini.icons',
  },
  config = function()
    local wk = require('which-key')

    wk.setup({
      preset = 'helix',
      show_help = false,
      plugins = {
        spelling = {
          enabled = false,
        },
      },
    })

    wk.add({
      { '#', hidden = true },
      { '*', hidden = true },
      { '/', hidden = true },
      { '<leader>n', hidden = true },
      { '?', hidden = true },
      { 'N', hidden = true },
      { 'g#', hidden = true },
      { 'g*', hidden = true },
      { 'h', hidden = true },
      { 'j', hidden = true },
      { 'k', hidden = true },
      { 'l', hidden = true },
      { 'n', hidden = true },
      { '<2-LeftMouse>', desc = 'Match double clicked word' },
      { '<C-f>', desc = 'snacks', icon = { cat = 'filetype', name = 'fzf' } },
      { '<leader>e', desc = 'rip substitute', icon = { icon = '󰬳', color = 'orange' } },
      { '<leader>o', icon = { cat = 'lsp', name = 'Reference' } },
      { '<leader>r', desc = 'substitute word(s)', icon = { icon = '󰬳', color = 'orange' } },
      { '<leader>a', group = 'ai', icon = { cat = 'filetype', name = 'robot' } },
      { '<leader>ab', icon = { icon = '󱀹', color = 'blue' } },
      { '<leader>ad', icon = { icon = '', color = 'red' } },
      { '<leader>al', icon = { icon = '󰚩', color = 'yellow' } },
      { '<leader>ap', icon = { icon = '󰉻', color = 'purple' } },
      { '<leader>as', desc = 'send selection', icon = { icon = '󰵴', color = 'cyan' }, mode = 'v' },
      { '<leader>at', icon = { icon = '󰵴', color = 'cyan' } },
      { '<leader>d', group = 'debug', icon = { cat = 'filetype', name = 'dapui_breakpoints' } },
      { '<leader>de', icon = { icon = '', color = 'red' } },
      { '<leader>dh', icon = { icon = '', color = 'yellow' } },
      { '<leader>dl', icon = { icon = '', color = 'green' } },
      { '<leader>do', icon = { icon = '', color = 'cyan' } },
      { '<leader>dr', icon = { icon = '', color = 'orange' } },
      { '<leader>dv', icon = { icon = '󰌨', color = 'purple' } },
      { '<leader>dt', icon = { icon = '', color = 'blue' } },
      { '<leader>du', icon = { icon = '', color = 'yellow' } },
      { '<leader>db', icon = { icon = '', color = 'red' } },
      { '<leader>dB', icon = { icon = '', color = 'red' } },
      { '<leader>dS', icon = { icon = '', color = 'green' } },
      { '<leader>ds', icon = { icon = '', color = 'green' } },
      { 'gd', desc = 'diagnostics', icon = { icon = '', color = '' } },
      { 'gdd', icon = { icon = '󰧮', color = 'red' } },
      { 'gdf', icon = { icon = '', color = 'blue' } },
      { 'gdn', icon = { icon = '󰮱', color = 'yellow' } },
      { 'gdp', icon = { icon = '󰮳', color = 'yellow' } },
      { 'gdw', icon = { icon = '󱔘', color = 'red' } },
      { '<leader>f', icon = { icon = '󰱼', color = 'blue' } },
      { '<leader>b', icon = { icon = '󰱼', color = 'cyan' } },
      { '<leader>s', icon = { icon = '󱎸', color = 'green' } },
      { '<leader>w', icon = { icon = '󱎸', color = 'green' } },
      { '<leader>g', icon = { cat = 'filetype', name = 'git' } },
      { '<leader>h', desc = 'git', icon = { cat = 'filetype', name = 'git' } },
      { '<leader>hb', icon = { icon = '', color = 'green' } },
      { '<leader>hf', icon = { icon = '', color = 'yellow' } },
      { '<leader>hF', icon = { icon = '', color = 'yellow' } },
      { '<leader>hn', icon = { icon = '󰮱', color = 'green' } },
      { '<leader>hp', icon = { icon = '󰮳', color = 'green' } },
      { '<leader>hr', icon = { icon = '', color = 'red' } },
      { '<leader>hR', icon = { icon = '', color = 'red' } },
      { '<leader>hs', icon = { icon = '', color = 'green' } },
      { '<leader>hS', icon = { icon = '󰕌', color = 'yellow' } },
      { '<leader>ht', icon = { icon = '󱂧', color = 'orange' } },
      { '<leader>hB', icon = { icon = '󰕌', color = 'yellow' } },
      { '<leader>hI', icon = { icon = '', color = 'blue' } },
      { '<leader>hi', icon = { icon = '', color = 'blue' } },
      { '<leader>hl', icon = { cat = 'filetype', name = 'qf' } },
      { '<leader>hd', desc = 'diff', icon = { icon = '', color = 'purple' } },
      { '<leader>hdt', icon = { icon = '', color = 'purple' } },
      { '<leader>hdo', icon = { icon = '', color = 'purple' } },
      { '<leader>l', desc = 'toggle loclist', icon = { cat = 'filetype', name = 'qf' } },
      { '<leader>q', desc = 'toggle quickfix', icon = { cat = 'filetype', name = 'qf' } },
      { '<leader>t', desc = 'testing', icon = { icon = '󰙨', color = 'red' } },
      { '<leader>ta', icon = { icon = '󱘖', color = 'yellow' } },
      { '<leader>tf', icon = { icon = '', color = 'green' } },
      { '<leader>th', icon = { icon = '', color = 'yellow' } },
      { '<leader>tl', icon = { icon = '', color = 'green' } },
      { '<leader>tt', icon = { icon = '󰣉', color = 'green' } },
      { '<leader>tn', icon = { icon = '󰮱', color = 'green' } },
      { '<leader>tp', icon = { icon = '󰮳', color = 'green' } },
      { '<leader>to', icon = { icon = '', color = 'yellow' } },
      { '<leader>ts', icon = { icon = '', color = 'yellow' } },
      { '<leader>tw', icon = { icon = '󱎴', color = 'orange' } },
      { '<leader>x', desc = 'execute current line', icon = { cat = 'filetype', name = 'lua' } },
      { '<leader>y', desc = 'copy to system clipboard', icon = { cat = 'lsp', name = 'Snippet' } },
      { 'Y', desc = 'Yank to end of line' },
      { 'gl', desc = 'lsp', icon = { cat = 'lsp', name = 'Event' } },
      { 'gr', desc = 'selection', icon = { cat = 'lsp', name = 'TypeParameter' } },
    })
  end,
}
