#!/usr/bin/env sh

sudo yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^CheatSheet$" manage=off
yabai -m rule --add app="^Pastebot$" manage=off
yabai -m rule --add app="^Kaleidoscope$" manage=off
yabai -m rule --add app="^Drop$" manage=off
yabai -m rule --add app="^Home$" manage=off
yabai -m rule --add app="^Hammerspoon$" manage=off
yabai -m rule --add app="^MacGPT$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Deliveries$" manage=off
yabai -m rule --add app="^Velja$" manage=off
yabai -m rule --add app="^Keyboard Setup" manage=off
yabai -m rule --add app="^Bartender" manage=off
yabai -m rule --add app="^Camtasia" manage=off
yabai -m rule --add app="^Snagit" manage=off
yabai -m rule --add app="^Raycast" manage=off
yabai -m rule --add app="^krisp" manage=off
yabai -m rule --add app="^RODE" manage=off
yabai -m rule --add app="^Backblaze" manage=off

echo "yabai configuration loaded..."
