#
# aeorospace.toml
# https://nikitabobko.github.io/AeroSpace/
#

after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[gaps]
inner.horizontal = 3
inner.vertical =   3
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[[on-window-detected]]
if.app-name-regex-substring = '^1Password|^Deliveries|^Hammerspoon|^Music|^Snagit|^Simulator'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = '^Alacritty'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = '^Asana|^zoom\.us'
check-further-callbacks = true
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = '^Mimestream|^Mail|^Calendar'
check-further-callbacks = true
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = '^Things|^Messages|^Reminders'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = '^Slack'
check-further-callbacks = true
run = ['move-node-to-workspace 6']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'

[key-mapping]
preset = 'qwerty'

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

shift-alt-0 = 'balance-sizes'
shift-alt-f = 'fullscreen'
alt-shift-t = 'layout floating tiling'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-ctrl-h = 'join-with left'
alt-shift-ctrl-j = 'join-with down'
alt-shift-ctrl-k = 'join-with up'
alt-shift-ctrl-l = 'join-with right'

alt-shift-left = 'resize smart -75'
alt-shift-right = 'resize smart +75'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
[mode.service.binding]
r = ['reload-config', 'mode main']
esc = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
