require('wassim/autocmds')
require('wassim/statusline')
require('wassim/tabline')
require('wassim/lsp')
require('wassim/treesitter')
require('wassim/completions')
require('wassim/snippets')
require('wassim/mappings')
